$(document).ready(function(){
  // Add smooth scrolling to all links
  $("a").on('click', function(event) {

    // Make sure this.hash has a value before overriding default behavior
    if (this.hash !== "") {
      // Prevent default anchor click behavior
      event.preventDefault();

      // Store hash
      var hash = this.hash;

      // Using jQuery's animate() method to add smooth page scroll
      // The optional number (800) specifies the number of milliseconds it takes to scroll to the specified area
      $('html, body').animate({
        scrollTop: $(hash).offset().top
      }, 800, function(){
   
        // Add hash (#) to URL when done scrolling (default click behavior)
        window.location.hash = hash;
      });
    } // End if
  });
});
$(document).ready(function(){
    $("#1").click(function(){
        $("#one").fadeIn("slow");
        $("#two").hide();
        $("#three").hide();
        $("#four").hide();
        $("#six").hide();
        $("#seven").hide();
        $("#eight").hide();
        $("#nine").hide();
        $("#ten").hide();
        $("#eleven").hide();
        $("#twelve").hide();
        $("#thirteen").hide();
        $("#fourteen").hide();
        $("#fifteen").hide();
        $("#sixteen").hide();
        $("#seventeen").hide();
        $("#eighteen").hide();
        $("#nineteen").hide();
        $("#twenty").hide();
    });
    $("#2").click(function(){
        $("#two").fadeIn("slow");
        $("#one").hide();
        $("#three").hide();
        $("#four").hide();
        $("#six").hide();
        $("#seven").hide();
        $("#eight").hide();
        $("#nine").hide();
        $("#ten").hide();
        $("#eleven").hide();
        $("#twelve").hide();
        $("#thirteen").hide();
        $("#fourteen").hide();
        $("#fifteen").hide();
        $("#sixteen").hide();
        $("#seventeen").hide();
        $("#eighteen").hide();
        $("#nineteen").hide();
        $("#twenty").hide();
    });
    $("#3").click(function(){
        $("#three").fadeIn("slow");
        $("#one").hide();
        $("#two").hide();
        $("#four").hide();
        $("#six").hide();
        $("#seven").hide();
        $("#eight").hide();
        $("#nine").hide();
        $("#ten").hide();
        $("#eleven").hide();
        $("#twelve").hide();
        $("#thirteen").hide();
        $("#fourteen").hide();
        $("#fifteen").hide();
        $("#sixteen").hide();
        $("#seventeen").hide();
        $("#eighteen").hide();
        $("#nineteen").hide();
        $("#twenty").hide();
    });
    
    $("#4").click(function(){
        $("#four").fadeIn("slow");
        $("#one").hide();
        $("#three").hide();
        $("#two").hide();
        $("#six").hide();
        $("#seven").hide();
        $("#eight").hide();
        $("#nine").hide();
        $("#ten").hide();
        $("#eleven").hide();
        $("#twelve").hide();
        $("#thirteen").hide();
        $("#fourteen").hide();
        $("#fifteen").hide();
        $("#sixteen").hide();
        $("#seventeen").hide();
        $("#eighteen").hide();
        $("#nineteen").hide();
        $("#twenty").hide();
    });
    
    $("#6").click(function(){
        $("#six").fadeIn("slow");
        $("#one").hide();
        $("#three").hide();
        $("#four").hide();
        $("#two").hide();
        $("#seven").hide();
        $("#eight").hide();
        $("#nine").hide();
        $("#ten").hide();
        $("#eleven").hide();
        $("#twelve").hide();
        $("#thirteen").hide();
        $("#fourteen").hide();
        $("#fifteen").hide();
        $("#sixteen").hide();
        $("#seventeen").hide();
        $("#eighteen").hide();
        $("#nineteen").hide();
        $("#twenty").hide();
    });
    
    $("#7").click(function(){
        $("#seven").fadeIn("slow");
        $("#one").hide();
        $("#three").hide();
        $("#four").hide();
        $("#six").hide();
        $("#two").hide();
        $("#eight").hide();
        $("#nine").hide();
        $("#ten").hide();
        $("#eleven").hide();
        $("#twelve").hide();
        $("#thirteen").hide();
        $("#fourteen").hide();
        $("#fifteen").hide();
        $("#sixteen").hide();
        $("#seventeen").hide();
        $("#eighteen").hide();
        $("#nineteen").hide();
        $("#twenty").hide();
    });
    
    $("#8").click(function(){
        $("#eight").fadeIn("slow");
        $("#one").hide();
        $("#three").hide();
        $("#four").hide();
        $("#six").hide();
        $("#seven").hide();
        $("#two").hide();
        $("#nine").hide();
        $("#ten").hide();
        $("#eleven").hide();
        $("#twelve").hide();
        $("#thirteen").hide();
        $("#fourteen").hide();
        $("#fifteen").hide();
        $("#sixteen").hide();
        $("#seventeen").hide();
        $("#eighteen").hide();
        $("#nineteen").hide();
        $("#twenty").hide();
    });
    
    $("#9").click(function(){
        $("#nine").fadeIn("slow");
        $("#one").hide();
        $("#three").hide();
        $("#four").hide();
        $("#six").hide();
        $("#seven").hide();
        $("#eight").hide();
        $("#two").hide();
        $("#ten").hide();
        $("#eleven").hide();
        $("#twelve").hide();
        $("#thirteen").hide();
        $("#fourteen").hide();
        $("#fifteen").hide();
        $("#sixteen").hide();
        $("#seventeen").hide();
        $("#eighteen").hide();
        $("#nineteen").hide();
        $("#twenty").hide();
    });
    
    $("#10").click(function(){
        $("#ten").fadeIn("slow");
        $("#one").hide();
        $("#three").hide();
        $("#four").hide();
        $("#six").hide();
        $("#seven").hide();
        $("#eight").hide();
        $("#nine").hide();
        $("#two").hide();
        $("#eleven").hide();
        $("#twelve").hide();
        $("#thirteen").hide();
        $("#fourteen").hide();
        $("#fifteen").hide();
        $("#sixteen").hide();
        $("#seventeen").hide();
        $("#eighteen").hide();
        $("#nineteen").hide();
        $("#twenty").hide();
    });
    
    $("#11").click(function(){
        $("#eleven").fadeIn("slow");
        $("#one").hide();
        $("#three").hide();
        $("#four").hide();
        $("#six").hide();
        $("#seven").hide();
        $("#eight").hide();
        $("#nine").hide();
        $("#ten").hide();
        $("#two").hide();
        $("#twelve").hide();
        $("#thirteen").hide();
        $("#fourteen").hide();
        $("#fifteen").hide();
        $("#sixteen").hide();
        $("#seventeen").hide();
        $("#eighteen").hide();
        $("#nineteen").hide();
        $("#twenty").hide();
    });
    
    $("#12").click(function(){
        $("#twelve").fadeIn("slow");
        $("#one").hide();
        $("#three").hide();
        $("#four").hide();
        $("#six").hide();
        $("#seven").hide();
        $("#eight").hide();
        $("#nine").hide();
        $("#ten").hide();
        $("#eleven").hide();
        $("#two").hide();
        $("#thirteen").hide();
        $("#fourteen").hide();
        $("#fifteen").hide();
        $("#sixteen").hide();
        $("#seventeen").hide();
        $("#eighteen").hide();
        $("#nineteen").hide();
        $("#twenty").hide();
    });
    
    $("#13").click(function(){
        $("#thirteen").fadeIn("slow");
        $("#one").hide();
        $("#three").hide();
        $("#four").hide();
        $("#six").hide();
        $("#seven").hide();
        $("#eight").hide();
        $("#nine").hide();
        $("#ten").hide();
        $("#eleven").hide();
        $("#twelve").hide();
        $("#two").hide();
        $("#fourteen").hide();
        $("#fifteen").hide();
        $("#sixteen").hide();
        $("#seventeen").hide();
        $("#eighteen").hide();
        $("#nineteen").hide();
        $("#twenty").hide();
    });
    
    $("#14").click(function(){
        $("#fourteen").fadeIn("slow");
        $("#one").hide();
        $("#three").hide();
        $("#four").hide();
        $("#six").hide();
        $("#seven").hide();
        $("#eight").hide();
        $("#nine").hide();
        $("#ten").hide();
        $("#eleven").hide();
        $("#twelve").hide();
        $("#thirteen").hide();
        $("#two").hide();
        $("#fifteen").hide();
        $("#sixteen").hide();
        $("#seventeen").hide();
        $("#eighteen").hide();
        $("#nineteen").hide();
        $("#twenty").hide();
    });
    
    $("#15").click(function(){
        $("#fifteen").fadeIn("slow");
        $("#one").hide();
        $("#three").hide();
        $("#four").hide();
        $("#six").hide();
        $("#seven").hide();
        $("#eight").hide();
        $("#nine").hide();
        $("#ten").hide();
        $("#eleven").hide();
        $("#twelve").hide();
        $("#thirteen").hide();
        $("#fourteen").hide();
        $("#two").hide();
        $("#sixteen").hide();
        $("#seventeen").hide();
        $("#eighteen").hide();
        $("#nineteen").hide();
        $("#twenty").hide();
    });
    
    $("#16").click(function(){
        $("#sixteen").fadeIn("slow");
        $("#one").hide();
        $("#three").hide();
        $("#four").hide();
        $("#six").hide();
        $("#seven").hide();
        $("#eight").hide();
        $("#nine").hide();
        $("#ten").hide();
        $("#eleven").hide();
        $("#twelve").hide();
        $("#thirteen").hide();
        $("#fourteen").hide();
        $("#fifteen").hide();
        $("#two").hide();
        $("#seventeen").hide();
        $("#eighteen").hide();
        $("#nineteen").hide();
        $("#twenty").hide();
    });
    
    $("#17").click(function(){
        $("#seventeen").fadeIn("slow");
        $("#one").hide();
        $("#three").hide();
        $("#four").hide();
        $("#six").hide();
        $("#seven").hide();
        $("#eight").hide();
        $("#nine").hide();
        $("#ten").hide();
        $("#eleven").hide();
        $("#twelve").hide();
        $("#thirteen").hide();
        $("#fourteen").hide();
        $("#fifteen").hide();
        $("#sixteen").hide();
        $("#two").hide();
        $("#eighteen").hide();
        $("#nineteen").hide();
        $("#twenty").hide();
    });
    
    $("#18").click(function(){
        $("#eighteen").fadeIn("slow");
        $("#one").hide();
        $("#three").hide();
        $("#four").hide();
        $("#six").hide();
        $("#seven").hide();
        $("#eight").hide();
        $("#nine").hide();
        $("#ten").hide();
        $("#eleven").hide();
        $("#twelve").hide();
        $("#thirteen").hide();
        $("#fourteen").hide();
        $("#fifteen").hide();
        $("#sixteen").hide();
        $("#seventeen").hide();
        $("#two").hide();
        $("#nineteen").hide();
        $("#twenty").hide();
    });
    
    $("#19").click(function(){
        $("#nineteen").fadeIn("slow");
        $("#one").hide();
        $("#three").hide();
        $("#four").hide();
        $("#six").hide();
        $("#seven").hide();
        $("#eight").hide();
        $("#nine").hide();
        $("#ten").hide();
        $("#eleven").hide();
        $("#twelve").hide();
        $("#thirteen").hide();
        $("#fourteen").hide();
        $("#fifteen").hide();
        $("#sixteen").hide();
        $("#seventeen").hide();
        $("#eighteen").hide();
        $("#two").hide();
        $("#twenty").hide();
    });
    
    $("#20").click(function(){
        $("#twenty").fadeIn("slow");
        $("#one").hide();
        $("#three").hide();
        $("#four").hide();
        $("#six").hide();
        $("#seven").hide();
        $("#eight").hide();
        $("#nine").hide();
        $("#ten").hide();
        $("#eleven").hide();
        $("#twelve").hide();
        $("#thirteen").hide();
        $("#fourteen").hide();
        $("#fifteen").hide();
        $("#sixteen").hide();
        $("#seventeen").hide();
        $("#eighteen").hide();
        $("#nineteen").hide();
        $("#two").hide();
    });
});